// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/login","id":"1"},"2":{"path":"/","id":"2"},"3":{"path":"/","redirect":"/dashboard","parentId":"2","id":"3"},"4":{"path":"/dashboard","parentId":"2","id":"4"},"5":{"path":"/devices","parentId":"2","id":"5"},"6":{"path":"/borrow","parentId":"2","id":"6"},"7":{"path":"/returned","parentId":"2","id":"7"},"8":{"path":"/profile","parentId":"2","id":"8"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__Login__index" */'@/pages/Login/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "layouts__BasicLayout" */'@/layouts/BasicLayout.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Devices__index" */'@/pages/Devices/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Borrow__index" */'@/pages/Borrow/index.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Returned__index" */'@/pages/Returned/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Profile__index" */'@/pages/Profile/index.tsx')),
},
  };
}
